global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prom:9090
  - job_name: otel_collector
    static_configs:
      - targets:
          - otel:8889
  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets:
          - loki:3100
